package com.powerservice.managermag.anagrafiche.utilities;

import java.util.ArrayList;

public class General {

    // Metodo statico che restituisce un ArrayList di stringhe con i nomi degli stati del mondo
    public static ArrayList<String> getStatiDelMondo() {
        ArrayList<String> statiDelMondo = new ArrayList<>();
        statiDelMondo.add("(Nessuno)");
        statiDelMondo.add("Afghanistan");
        statiDelMondo.add("Albania");
        statiDelMondo.add("Algeria");
        statiDelMondo.add("Andorra");
        statiDelMondo.add("Angola");
        statiDelMondo.add("Antigua e Barbuda");
        statiDelMondo.add("Arabia Saudita");
        statiDelMondo.add("Argentina");
        statiDelMondo.add("Armenia");
        statiDelMondo.add("Australia");
        statiDelMondo.add("Austria");
        statiDelMondo.add("Azerbaigian");
        statiDelMondo.add("Bahamas");
        statiDelMondo.add("Bahrein");
        statiDelMondo.add("Bangladesh");
        statiDelMondo.add("Barbados");
        statiDelMondo.add("Belgio");
        statiDelMondo.add("Belize");
        statiDelMondo.add("Benin");
        statiDelMondo.add("Bhutan");
        statiDelMondo.add("Bielorussia");
        statiDelMondo.add("Birmania");
        statiDelMondo.add("Bolivia");
        statiDelMondo.add("Bosnia ed Erzegovina");
        statiDelMondo.add("Botswana");
        statiDelMondo.add("Brasile");
        statiDelMondo.add("Brunei");
        statiDelMondo.add("Bulgaria");
        statiDelMondo.add("Burkina Faso");
        statiDelMondo.add("Burundi");
        statiDelMondo.add("Cambogia");
        statiDelMondo.add("Camerun");
        statiDelMondo.add("Canada");
        statiDelMondo.add("Capo Verde");
        statiDelMondo.add("Ciad");
        statiDelMondo.add("Cile");
        statiDelMondo.add("Cina");
        statiDelMondo.add("Cipro");
        statiDelMondo.add("Colombia");
        statiDelMondo.add("Comore");
        statiDelMondo.add("Corea del Nord");
        statiDelMondo.add("Corea del Sud");
        statiDelMondo.add("Costa d'Avorio");
        statiDelMondo.add("Costa Rica");
        statiDelMondo.add("Croazia");
        statiDelMondo.add("Cuba");
        statiDelMondo.add("Danimarca");
        statiDelMondo.add("Dominica");
        statiDelMondo.add("Ecuador");
        statiDelMondo.add("Egitto");
        statiDelMondo.add("El Salvador");
        statiDelMondo.add("Emirati Arabi Uniti");
        statiDelMondo.add("Eritrea");
        statiDelMondo.add("Estonia");
        statiDelMondo.add("Eswatini");
        statiDelMondo.add("Etiopia");
        statiDelMondo.add("Fiji");
        statiDelMondo.add("Filippine");
        statiDelMondo.add("Finlandia");
        statiDelMondo.add("Francia");
        statiDelMondo.add("Gabon");
        statiDelMondo.add("Gambia");
        statiDelMondo.add("Georgia");
        statiDelMondo.add("Germania");
        statiDelMondo.add("Ghana");
        statiDelMondo.add("Giamaica");
        statiDelMondo.add("Giappone");
        statiDelMondo.add("Gibuti");
        statiDelMondo.add("Giordania");
        statiDelMondo.add("Grecia");
        statiDelMondo.add("Grenada");
        statiDelMondo.add("Guatemala");
        statiDelMondo.add("Guinea");
        statiDelMondo.add("Guinea Equatoriale");
        statiDelMondo.add("Guinea-Bissau");
        statiDelMondo.add("Guyana");
        statiDelMondo.add("Haiti");
        statiDelMondo.add("Honduras");
        statiDelMondo.add("India");
        statiDelMondo.add("Indonesia");
        statiDelMondo.add("Iran");
        statiDelMondo.add("Iraq");
        statiDelMondo.add("Irlanda");
        statiDelMondo.add("Islanda");
        statiDelMondo.add("Israele");
        statiDelMondo.add("Italia");
        statiDelMondo.add("Jamaica");
        statiDelMondo.add("Kazakistan");
        statiDelMondo.add("Kenya");
        statiDelMondo.add("Kirghizistan");
        statiDelMondo.add("Kiribati");
        statiDelMondo.add("Kosovo");
        statiDelMondo.add("Kuwait");
        statiDelMondo.add("Laos");
        statiDelMondo.add("Lesotho");
        statiDelMondo.add("Lettonia");
        statiDelMondo.add("Libano");
        statiDelMondo.add("Liberia");
        statiDelMondo.add("Libia");
        statiDelMondo.add("Liechtenstein");
        statiDelMondo.add("Lituania");
        statiDelMondo.add("Lussemburgo");
        statiDelMondo.add("Macedonia del Nord");
        statiDelMondo.add("Madagascar");
        statiDelMondo.add("Malawi");
        statiDelMondo.add("Malaysia");
        statiDelMondo.add("Maldive");
        statiDelMondo.add("Mali");
        statiDelMondo.add("Malta");
        statiDelMondo.add("Marocco");
        statiDelMondo.add("Marshall");
        statiDelMondo.add("Mauritania");
        statiDelMondo.add("Mauritius");
        statiDelMondo.add("Messico");
        statiDelMondo.add("Micronesia");
        statiDelMondo.add("Moldavia");
        statiDelMondo.add("Monaco");
        statiDelMondo.add("Mongolia");
        statiDelMondo.add("Montenegro");
        statiDelMondo.add("Mozambico");
        statiDelMondo.add("Namibia");
        statiDelMondo.add("Nauru");
        statiDelMondo.add("Nepal");
        statiDelMondo.add("Nicaragua");
        statiDelMondo.add("Niger");
        statiDelMondo.add("Nigeria");
        statiDelMondo.add("Norvegia");
        statiDelMondo.add("Nuova Zelanda");
        statiDelMondo.add("Oman");
        statiDelMondo.add("Paesi Bassi");
        statiDelMondo.add("Pakistan");
        statiDelMondo.add("Palau");
        statiDelMondo.add("Palestina");
        statiDelMondo.add("Panama");
        statiDelMondo.add("Papua Nuova Guinea");
        statiDelMondo.add("Paraguay");
        statiDelMondo.add("Perù");
        statiDelMondo.add("Polonia");
        statiDelMondo.add("Portogallo");
        statiDelMondo.add("Qatar");
        statiDelMondo.add("Regno Unito");
        statiDelMondo.add("Repubblica Centrafricana");
        statiDelMondo.add("Repubblica Ceca");
        statiDelMondo.add("Repubblica Democratica del Congo");
        statiDelMondo.add("Repubblica Dominicana");
        statiDelMondo.add("Romania");
        statiDelMondo.add("Ruanda");
        statiDelMondo.add("Russia");
        statiDelMondo.add("Saint Kitts e Nevis");
        statiDelMondo.add("Saint Vincent e Grenadine");
        statiDelMondo.add("Salomone");
        statiDelMondo.add("Samoa");
        statiDelMondo.add("San Marino");
        statiDelMondo.add("Santa Lucia");
        statiDelMondo.add("São Tomé e Príncipe");
        statiDelMondo.add("Senegal");
        statiDelMondo.add("Serbia");
        statiDelMondo.add("Seychelles");
        statiDelMondo.add("Sierra Leone");
        statiDelMondo.add("Singapore");
        statiDelMondo.add("Siria");
        statiDelMondo.add("Slovacchia");
        statiDelMondo.add("Slovenia");
        statiDelMondo.add("Somalia");
        statiDelMondo.add("Spagna");
        statiDelMondo.add("Sri Lanka");
        statiDelMondo.add("Stati Uniti d'America");
        statiDelMondo.add("Sudafrica");
        statiDelMondo.add("Sudan");
        statiDelMondo.add("Sudan del Sud");
        statiDelMondo.add("Suriname");
        statiDelMondo.add("Svezia");
        statiDelMondo.add("Svizzera");
        statiDelMondo.add("Swaziland");
        statiDelMondo.add("Tagikistan");
        statiDelMondo.add("Tanzania");
        statiDelMondo.add("Thailandia");
        statiDelMondo.add("Timor Est");
        statiDelMondo.add("Togo");
        statiDelMondo.add("Tonga");
        statiDelMondo.add("Trinidad e Tobago");
        statiDelMondo.add("Tunisia");
        statiDelMondo.add("Turchia");
        statiDelMondo.add("Turkmenistan");
        statiDelMondo.add("Tuvalu");
        statiDelMondo.add("Ucraina");
        statiDelMondo.add("Uganda");
        statiDelMondo.add("Ungheria");
        statiDelMondo.add("Uruguay");
        statiDelMondo.add("Uzbekistan");
        statiDelMondo.add("Vanuatu");
        statiDelMondo.add("Venezuela");
        statiDelMondo.add("Vietnam");
        statiDelMondo.add("Yemen");
        statiDelMondo.add("Zambia");
        statiDelMondo.add("Zimbabwe");

        return statiDelMondo;
    }
}
